version: '2'
services:
  web:
    restart: always
    build:
     context: .
     dockerfile: Dockerfile
    container_name: lunarhacks
    ports:
     - "80:80"
    env_file: .env
    environment:
     - NODE_ENV=production
     - PORT=80
    depends_on:
     - db
    volumes:
     - /data/secrets:/opt/lunarhacks/secrets
  db:
    image: mongo:3.6
    restart: always
    expose:
      - "27017"
    volumes:
      - /data/db:/data/db
